baseURL = "https://vertcoin.org/"
DefaultContentLanguage = "en"
title = "Vertcoin"
theme = "elate"

[params]
  [params.navigation]
    brand = "Vertcoin"
 
  [params.intro]

      [[params.intro.item]]
        url = "/wallets"
        icon = "icon-wallet"

      [[params.intro.item]]
        url = "#"
        icon = "icon-diamond"

      [[params.intro.item]]
        url = "/trade"
        icon = "icon-rocket"
        
      [[params.intro.item]]
        url = "#"
        icon = "icon-wrench"
        
      [[params.intro.item]]
        url = "https://docs.vertcoin.org"
        icon = "icon-question"
        
      [[params.intro.item]]
        url = "#"
        icon = "icon-basket-loaded"

      [params.intro.video]
        enable = true
        icon = "icon-play2"
        url = "https://www.youtube.com/watch?v=80kzNwYGMpg"
  
  [params.services]
    enable = true

    [[params.services.item]]
      icon = "icon-people"

    [[params.services.item]]
      icon = "icon-lock"
      
    [[params.services.item]]
      icon = "icon-energy"

    [[params.services.item]]      
      icon = "icon-heart"
      
    [[params.services.item]]  
      icon = "icon-bubble"
      
    [[params.services.item]]
      icon = "icon-chemistry"
      
  # Counters section
  [params.counters]
    enable = true
    background = "full_image_1.jpg"

    [[params.counters.item]]
      icon = "icon-refresh"
      from = 42300000
      to = 42343150
      interval = 2000
      speed = 50000

    [[params.counters.item]]
      icon = "icon-social-reddit"
      from = 0
      to = 30604
      interval = 500
      speed = 10000

    [[params.counters.item]]
      icon = "icon-speedometer"
      from = 13700000
      to = 13771410
      interval = 3000
      speed = 7000

    [[params.counters.item]]
      icon = "icon-social-twitter"
      from = 0
      to = 71500
      interval = 5000
      speed = 10000
      
  [params.about]
    enable = true
  
    [[params.about.item]]
      name = "James Lovejoy"
      img = "james.jpg"
      alt = "James Lovejoy"
      social = [
        ["icon-twitter", "https://twitter.com/jamesl22"],
        ["icon-github", "https://github.com/metalicjames/"]
      ]

    [[params.about.item]]
      name = "Joe Straub"
      img = "joe.jpg"
      alt = "Zemrys"
      social = [
        ["icon-github", "https://github.com/zemrys"]
      ]

    [[params.about.item]]
      name = "Eric Kubik"
      img = "eric.png"
      alt = "Eric"
      social = [
        ["icon-twitter", "https://twitter.com/etang600"]
      ]
      
    [[params.about.item]]
      name = "Star Im"
      img = "star.jpg"
      alt = "Star"
      social = []  
      
    [[params.about.item]]
      name = "Bryan Goodson"
      img = "bryan.jpg"
      alt = "Bryan Goodson"
      social = [
        ["icon-twitter", "https://twitter.com/BryanGoodson"],
        ["icon-github", "https://github.com/Bryangoodson"],
        ["icon-linkedin", "https://www.linkedin.com/in/bgoodson"]
      ]  
      
    [[params.about.item]]
      name = "Gert-Jaap Glasbergen"
      img = "gertjaap.png"
      alt = "Gert-Jaap Glasbergen"
      social = [
        ["icon-twitter", "https://twitter.com/gertjaap"],
        ["icon-github", "https://github.com/gertjaap"],
        ["icon-linkedin", "https://www.linkedin.com/in/gertjaap"]
      ]  
      
    [[params.about.item]]
      name = "Alex Turek"
      img = "alex.jpg"
      alt = "Alex Turek"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/turekaj/"]
      ] 
      
    [[params.about.item]]
      name = "jk_14"
      img = "person1.jpg"
      alt = "jk_14"
      social = []  
      
    [[params.about.item]]
      name = "pknight"
      img = "person2.jpg"
      alt = "pknight"
      social = [] 
      
    [[params.about.item]]
      name = "Adam Rivera"
      img = "adam.jpg"
      alt = "a432511"
      social = [
        ["icon-twitter", "https://twitter.com/a432511"],
        ["icon-linkedin", "https://www.linkedin.com/in/adammrivera/"]
      ] 
      
    [[params.about.item]]
      name = "Daiki"
      img = "daiki.jpg"
      alt = "Daiki"
      social = [] 
      
    [[params.about.item]]
      name = "The Community"
      img = "placeholder.png"
      alt = "Community"
      social = [] 
      
  [params.footer]
    enable = true
    copyright = '&copy; Vertcoin 2018<br> &copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'

